In [1]:
import numpy as np


In [2]:
arr=np.array([1,4,6,9])
print(arr)

[1 4 6 9]


In [4]:
print(np.zeros((4,9)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
print(np.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
print(np.full((2,4),8))

[[8 8 8 8]
 [8 8 8 8]]


In [16]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [18]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [19]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [21]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [22]:
arr=np.array([1.2,3.4,5.8,6.9])
print(arr.astype(int))

[1 3 5 6]
