In [1]:
import numpy as np

In [ ]:
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(arr[0,2])
print(arr[1,0])
print(arr[2,1])

3
4
8


In [5]:
print(arr[-1,-2])
print(arr[-1,-0])
print(arr[-2,-1])

8
7
6


In [7]:
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [9]:
print(arr[::2,::2])

[[1 3]
 [7 9]]


In [23]:
rand=np.random.default_rng(seed=42)
nums=rand.integers(1,15,size=8)
print(nums)

[ 2 11 10  7  7 13  2 10]


seed use for generate same number
ya  code random number generate kr ky dy gha 

In [25]:
rands=np.random.default_rng(seed=42)
numss=rands.integers(1,15,size=8)
print(numss)

[ 2 11 10  7  7 13  2 10]
